name: MedievoCore
version: ${project.version}
main: medievo.medievo.main
authors: [BGM]
description: Plugin core para El main
commands:
  tpa:
    usage: /tpa
    description: Envia tpa a otro jugador
  tpaccept:
    usage: /tpaccept
    description: Acepta una solicitud de tpa entrante
  tpcancel:
    usage: /tpcancel
    description: Rechaza una solicitud de tpa entrante
  coords:
    usage: /coords
    description: Comparte tus coordenadas en el chat